apiVersion: v1
kind: Namespace
metadata:
  name: class-demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: class-demo-app
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 100Mi
             cpu: 0.25

        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: class-demo-app

spec:

  selector:
    app: python-app

  ports:
    - name: http
      port: 80
      nodePort: 30011

  type: NodePort
